### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'osascript'

### ISSUE THREAD

**Issue by jramiresbrito** [TomAnthony/itermocil#124]
Hey guys, this is my first time trying to use itermocil.

After installing it through brew and add my .yml file, I got this error:

```bash
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/itermocil", line 33, in <module>
    sys.exit(load_entry_point('itermocil==1.0.0', 'console_scripts', 'itermocil')())
  File "/home/linuxbrew/.linuxbrew/Cellar/itermocil/1.0.2/libexec/lib/python3.10/site-packages/itermocil.py", line 731, in main
    instance = Itermocil(filepath, here=args.here, cwd=cwd)
  File "/home/linuxbrew/.linuxbrew/Cellar/itermocil/1.0.2/libexec/lib/python3.10/site-packages/itermocil.py", line 27, in __init__
    major_version = self.get_major_version()
  File "/home/linuxbrew/.linuxbrew/Cellar/itermocil/1.0.2/libexec/lib/python3.10/site-packages/itermocil.py", line 100, in get_major_version
    v = self.get_version_string()
  File "/home/linuxbrew/.linuxbrew/Cellar/itermocil/1.0.2/libexec/lib/python3.10/site-packages/itermocil.py", line 86, in get_version_string
    osa = subprocess.Popen(['osascript', '-'],
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'osascript'
```

The yml file is located in `~/.itermocil/myfile.yml`, and having the following:

```yml
windows:
  - name: myfile
    root: ~/.itermocil/myfile
    layout: tiled
    panes:
      - commands:
          - bundle install
          - rails s
      - commands:
          - tsc -w
      - commands:
          - yarn install
          - yarn start
      - commands:
          - docker-compose up
      - commands:
          - fswatch -0 -or app/graphql | xargs -0 -I {} yarn generate-types
```

## EDIT - Additional info

Package Manager
Brew: Homebrew 3.5.1

S.O
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:          20.04
Codename:     focal

**Comment by godbout** [comment]
i'm confused. AFAIK iTerm runs only on Mac. iTermocil is for iTerm. `osascript` is not found because it's a Mac thing and you seem to be running all of this on Linux. i don't get it. and i haven't had a drink yet. what are you trying to achieve?

**Comment by jramiresbrito** [comment]
Hmm, I see. As I'm not a Mac user I didn't realize that.
It seems like I'll need to go with [teamocil](https://github.com/remi/teamocil) instead.
Closing the issue.
