### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by idolize** [TomAnthony/itermocil#2]
I get the following error when trying to install:

```
 ~> brew install TomAnthony/brews/itermocil
==> Tapping TomAnthony/brews
Cloning into '/usr/local/Library/Taps/tomanthony/homebrew-brews'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 9 (delta 1), reused 9 (delta 1), pack-reused 0
Unpacking objects: 100% (9/9), done.
Checking connectivity... done.
Tapped 1 formula (31 files, 128K)
Error: undefined method `desc' for Formulary::Formulae::Itermocil:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/tomanthony/homebrew-brews/Formula/itermocil.rb:2:in `<class:Itermocil>'
/usr/local/Library/Taps/tomanthony/homebrew-brews/Formula/itermocil.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:177:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>
```

**Comment by TomAnthony** [comment]
Hi @idolize - thanks. I added the 'desc' field to the Formula as that seems to be the current suggested approach. However, it appears to break on non-recent Homebrew installs.

I just released an update, and commented this field out for now.

Let me know if it is working now. I'll leave this open until you confirm.

**Comment by TomAnthony** [comment]
This seems to be working fine now, so I'm going to close this. Let me know if not! :)

Thanks again for the feedback.
