### ISSUE TITLE
Maybe isn't working for nighlys of iterm2?

### ISSUE THREAD

**Issue by hedefalk** [TomAnthony/itermocil#30]
I had some issues that docker-machine didn't support my latest iterm2 because the api had changed. Maybe this is a similar issue:

https://github.com/docker/toolbox/issues/81#issuecomment-166917347

```
~ ❯❯❯ itermocil test                                                                                                                                                     ⏎
Traceback (most recent call last):
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil", line 6, in <module>
    main()
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 687, in main
    instance = Itermocil(filepath, here=args.here, cwd=cwd)
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 69, in __init__
    self.process_file()
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 528, in process_file
    self.arrange_panes(len(window['panes']), layout)
KeyError: 'panes'
```

I'm on Build 2.9.20151006-nightly.

The config is as simple as this:
```
~ ❯❯❯ cat .teamocil/test.yml                                                                                                                                             ⏎
windows:
  - name: test
    root: ~/
    layout: tiled
    commands:
      - pwd
~ ❯❯❯
```

**Comment by hedefalk** [comment]
Oh, sorry, that was not it. Get the same in iterm 2.1.4.

**Comment by hedefalk** [comment]
Oh, sorry, my bad. Incorrect yml I see now :)

**Comment by hedefalk** [comment]
This might be the most confusing ticket ever, but I re-tried iterm2 beta after realizing the above was just bad .yml by myself and now I get:


```
~ ❯❯❯ itermocil test
26:33: execution error: An error of type -10665 has occurred. (-10665)
Traceback (most recent call last):
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil", line 6, in <module>
    main()
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 687, in main
    instance = Itermocil(filepath, here=args.here, cwd=cwd)
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 28, in __init__
    major_version = self.get_major_version()
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 95, in get_major_version
    return float(v[:3])
ValueError: could not convert string to float:

```
That certainly seems like API issues against iterm2, right?

**Comment by hedefalk** [comment]
It actually worked with beta second time though…

**Comment by TomAnthony** [comment]
Well, this was an emotional roller-coaster...

I actually have a fix for that convert string to float issue (that happens when Applescript can't find iTerm, so even though iTermocil will not fail, in theory the Applescript shouldn't run correctly).

**Comment by hedefalk** [comment]
Yeah, weird. It only happened once and then everything worked just fine. Sorry for all the previous confusion. And thanks for an excellent tool. Will save me tons of time.

**Comment by jknightihiji** [comment]
I'm still experiencing this issue running iTerm2 v2.9.20160206.
