### ISSUE TITLE
itermocil fails when it checks iTerm build compiled from sources

### ISSUE THREAD

**Issue by alexfedoseev** [TomAnthony/itermocil#32]
Hi! I have iTerm, which were compiled from git master branch and  `itermocil` fails b/c `build` number is not `int` (it contains `git` string).

```
Traceback (most recent call last):
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil", line 6, in <module>
    main()
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 687, in main
    instance = Itermocil(filepath, here=args.here, cwd=cwd)
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 38, in __init__
    if (int(build) < 20150805):
ValueError: invalid literal for int() with base 10: 'git'
```

**Comment by DevilsNightsix** [comment]
Same issue on Mac OS X 10.11.3 with iTerm v 2.1.4

**Comment by TomAnthony** [comment]
I think this should now be fixed in the latest commits. I'll close this issue but please re-open if isn't working.
