### ISSUE TITLE
Can't find iTerm version

### ISSUE THREAD

**Issue by skurpi** [TomAnthony/itermocil#40]
Itermocil version: 0.1.8
iTerm version: Build 2.9.20160313
Python version: 2.7.10
OS X version: 10.11.2 (15C50)

When trying to start with the "even-horizontal" sample I get the following error:

```
$ itermocil sample
26:33: execution error: Can’t get application "iTerm". (-1728)
Traceback (most recent call last):
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil", line 6, in <module>
    main()
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 687, in main
    instance = Itermocil(filepath, here=args.here, cwd=cwd)
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 28, in __init__
    major_version = self.get_major_version()
  File "/usr/local/Cellar/itermocil/0.1.8/libexec/bin/itermocil.py", line 95, in get_major_version
    return float(v[:3])
ValueError: could not convert string to float:
```

This happens for whichever layout I've tried.
My theory is that the function "get_version_string" can't find the iTerm application:

```
 $ osascript -e 'get version of application "iTerm"'
 4:11: execution error: Can’t get application "iTerm". (-1728)
 $ osascript -e 'get version of application "iTerm2"'
 2.9.20160313
```
I don't remember installing iTerm in a different way than mentioned on iTerms website, and I only have one iTerm installed (https://github.com/TomAnthony/itermocil/issues/35).

When manually trying to edit the itermocil.py with the above change I get: 
> 47:53: syntax error: Expected end of line but found class name. (-2741)

But I don't have more time to put on this right now. Hope this helps

**Comment by TomAnthony** [comment]
This should be fixed in the latest pushes (I've not updated brew yet but will shortly).

**Comment by skurpi** [comment]
Cool, thanks for taking a look. Here is what I get when reinstalling and trying to run it. Running Iterm 3.0.1. Not sure if it's something else on my computer messing with it.

```
$ brew update
........

$ brew install TomAnthony/brews/itermocil
==> Installing itermocil from tomanthony/brews
Error: itermocil-0.1.8 already installed
To install this version, first `brew unlink itermocil`

$ brew unlink itermocil
Unlinking /usr/local/Cellar/itermocil/0.1.8... 2 symlinks removed

$ brew install TomAnthony/brews/itermocil
==> Installing itermocil from tomanthony/brews
==> Downloading https://github.com/TomAnthony/itermocil/archive/0.2.1.tar.gz
==> Downloading from https://codeload.github.com/TomAnthony/itermocil/tar.gz/0.2.1
######################################################################## 100.0%
==> Downloading https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.tar.gz
Already downloaded: /Users/skurpi/Library/Caches/Homebrew/itermocil--PyYAML-3.11.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/itermocil/0.2.1/libexec/vendor --single-version-externally-managed --record=installed.txt
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/itermocil/0.2.1/libexec --single-version-externally-managed --record=installed.txt
🍺  /usr/local/Cellar/itermocil/0.2.1: 54 files, 491.3K, built in 4 seconds

$ mkdir ~/.itermocil

$ itermocil --edit sample

$ itermocil sample
26:33: execution error: Can’t get application "iTerm". (-1728)
26:33: execution error: Can’t get application "iTerm". (-1728)
47:53: syntax error: Expected end of line but found class name. (-2741)

$ itermocil --version
0.2.1
```
