### ISSUE TITLE
python errors

### ISSUE THREAD

**Issue by fabriziogiordano** [TomAnthony/itermocil#7]
```
$ itermocil sample
Traceback (most recent call last):
  File "/usr/local/Cellar/itermocil/0.1.5/libexec/bin/itermocil", line 124, in <module>
    instance = Itermocil(filepath, here=args.here, cwd=cwd)
  File "/usr/local/Cellar/itermocil/0.1.5/libexec/bin/itermocil.py", line 73, in __init__
    self.process_file()
  File "/usr/local/Cellar/itermocil/0.1.5/libexec/bin/itermocil.py", line 375, in process_file
    for num, window in enumerate(teamocil_config['windows']):
KeyError: 'windows'
```

iTerm Build 2.1.1

**Comment by TomAnthony** [comment]
Hey @fabriziogiordano. Thanks for the report. 

I think I know the problem but if you could possibly post your YAM file for me to confirm that would be really helpful.

**Comment by TomAnthony** [comment]
I think I've fixed this in [this commit](https://github.com/TomAnthony/itermocil/commit/e7fda0f4a24fb90c5a6c7fe20a74ef05f369b6f0). I've not pushed this to homebrew yet but will soon.
