### ISSUE TITLE
itermocil hangs on macOS Mojave 

### ISSUE THREAD

**Issue by mlangenberg** [TomAnthony/itermocil#95]
This is probably related to my setup, but I would like some support in debugging this.

I saw this on High Sierra as well, hoped that Mojave would fix it, but it's still an issue.

How to reproduce:
- Reboot 13" MacBook Pro (2018)
- Happily use itermocil without problems
- _"... a few days later."_
- Run `itermocil`
- No output, command never exits.

 ```
itermocil --debug my_layout

(manual keyboard interrupt)

^CTraceback (most recent call last):
  File "/usr/local/Cellar/itermocil/0.2.1/libexec/bin/itermocil", line 6, in <module>
    main()
  File "/usr/local/Cellar/itermocil/0.2.1/libexec/bin/itermocil.py", line 729, in main
    instance = Itermocil(filepath, here=args.here, cwd=cwd)
  File "/usr/local/Cellar/itermocil/0.2.1/libexec/bin/itermocil.py", line 29, in __init__
    major_version = self.get_major_version()
  File "/usr/local/Cellar/itermocil/0.2.1/libexec/bin/itermocil.py", line 102, in get_major_version
    v = self.get_version_string()
  File "/usr/local/Cellar/itermocil/0.2.1/libexec/bin/itermocil.py", line 93, in get_version_string
    v = osa.communicate(version_script)[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1411, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1512, in _communicate_with_select
    rlist, wlist, xlist = select.select(read_set, write_set, [])
KeyboardInterrupt
```

I need to reboot my mac to make itermocil work again. 
Tested with iTerm2 Build 3.2.6.

**Comment by nitrocode** [comment]
I just ran my itermocil with iterm2 3.2.6 and it works for me on 10.13.6 osx high sierra. I don't have more information on how to debug this but it seems to be environment related. What's your python version?

    $ python --version
    2.7.15

**Comment by nitrocode** [comment]
@mlangenberg try upgrading to python `2.7.15`
